version: "3.9"
services:
  jekyll:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    command: >
      bundle exec jekyll serve -H "0.0.0.0"
